/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'happy_tree'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 5 */
struct node
{
  int field_0;
  int field_4;
  int visit_func;
};

/* 6 */
struct __cppobj arr_node : node
{
  int num;
  node **nodes;
};

